### ISSUE TITLE
When creating random PSK, don't use difficult to read chars

### ISSUE THREAD

**Issue by wifinigel** [WLAN-Pi/wlanpi-hotspot#11]
Some characters are ambiguous on-screen and may cause users to enter incorrect PSK values. Suggest that at least the following are removed or only capitalized version of the letters are used:

- 1  and l (lower case L) and I (upper case i)
- 0 and O

cc: @jiribrejcha

**Comment by joshschmelzle** [comment]
Fixed in d321fb965d83e2f8cf9491b4a8fe8088d58bd117 and released in v1.0.9.
